### ISSUE TITLE
How to decompile it

### ISSUE THREAD

**Issue by Dra-Ganzz** [KhanhNguyen9872/Piramid-deobf#1]
Hey please decrypt this file https://github.com/Bayu12345677/who-callme , I still don't understand how to decompile

**Comment by KhanhNguyen9872** [comment]
> Hey please decrypt this file https://github.com/Bayu12345677/who-callme , I still don't understand how to decompile

I can decode this code, but do you have his permission?

**Comment by Bayu12345677** [comment]
he is a criminal my brother 😂

**Comment by Bayu12345677** [comment]
> > Hey please decrypt this file https://github.com/Bayu12345677/who-callme , I still don't understand how to decompile
> 
> I can decode this code, but do you have his permission?

I am proud of you my brother 🙏, by the way i will release v3 of pyramid obf soon help me to develop it

**Comment by KhanhNguyen9872** [comment]
> > > Hey please decrypt this file https://github.com/Bayu12345677/who-callme , I still don't understand how to decompile
> > 
> > 
> > I can decode this code, but do you have his permission?
> 
> I am proud of you my brother 🙏, by the way i will release v3 of pyramid obf soon help me to develop it

okay, hope it release soon
i just review github from your brother, all of 'Run.py' can deobfuscate/decompile it

**Comment by Bayu12345677** [comment]
okay thank you my brother, for helping 🙏
